import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import Bombadil

// Template the agent starts from. `backend` is the Backend class from app.py, if any.
AppWindow {
    title: "Hello"
    subtitle: "generated by Bombadil"

    ColumnLayout {
        anchors.fill: parent
        spacing: 12
        Label { text: "Replace me"; color: Theme.fg; font: Theme.font }
        Button { text: "Click"; onClicked: console.log("clicked") }
    }
}
