title    Bombadil (smoke test: install to /dev/vda with a password)
sort-key 04
linux    /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux
initrd   /%INSTALL_DIR%/boot/x86_64/initramfs-linux.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% cow_spacesize=2G console=tty0 console=ttyS0,115200 bombadil.smoke=install-encrypted
