title    Bombadil (smoke test: refresh the Bombadil on /dev/vda)
sort-key 05
linux    /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux
initrd   /%INSTALL_DIR%/boot/x86_64/initramfs-linux.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% cow_spacesize=2G console=tty0 console=ttyS0,115200 bombadil.smoke=refresh
